results_dir: results/impala
input:
  train:
    Shangani: ../window-input/results/impala/Shangani_train.saf.idx
    MasaiMara: ../window-input/results/impala/MasaiMara_train.saf.idx
  test:
    Shangani: ../window-input/results/impala/Shangani_test.saf.idx
    MasaiMara: ../window-input/results/impala/MasaiMara_test.saf.idx
run: 
  pops: [MasaiMara, Shangani-MasaiMara]
  b: [500]
  w: [100, 250, 500]
realsfs:
  max_epochs: 500
winsfs:
  max_epochs: 500
winsfs_stream:
  shuffle_blocks: 100
  max_epochs: 10